name: Deploy Application
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm install
      - name: Install eleventy static generator
        run: npm install @11ty/eleventy -g
      - name: Build Application
        run: npx @11ty/eleventy
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Deploy files to aws
        run: aws s3 sync ./_site s3://banar.click/
      - name: Invalidate cloudfront cash
        run: aws cloudfront create-invalidation --distribution-id E2NLUFUVKTDLQK --paths '/*'
