name: Deploy Application
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm install
      - name: Install eleventy static generator
        run: npm install @11ty/eleventy -g
      - name: Build Application
        run: npx @11ty/eleventy
      - name: Print files
        run: ls -la
      - name: Install aws cli
        uses: chrislennon/action-aws-cli@v1.1
      - name: Auth aws
        run: aws s3 ls
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy files to aws
        run: aws s3 sync ./_site 's3://banar.click/'
