name: Deploy Application
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm install
      - name: Print files
        run: ls -la
