name: Deploy Application
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm install
      - name: Install eleventy static generator
        run: npm install @11ty/eleventy -g
      - name: Build Application
        run: npx @11ty/eleventy
      - name: Print files
        run: ls -la
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy files to aws
        run: aws s3 sync ./_site s3://banar.click/
